[package]
name = "scheme-rs-cml"
version = "0.1.0"
edition = "2024"

[dependencies]
scheme-rs = { git = "ssh://git@github.com/lshoravi/scheme-rs.git", branch = "linuss/port-readiness", features = ["async", "tokio"] }
tokio = { version = "1", features = ["full"] }
arc-swap = "1"
imbl = "3"
futures = "0.3"
rand = "0.9"

[dev-dependencies]
tokio = { version = "1", features = ["full", "test-util"] }
