(import (rnrs) (cml) (cml channels) (cml timers) (cml conditions))

(let ((ch (make-channel 1)))
  (do ((iter 0 (+ iter 1)))
      ((= iter 100))
    (send ch iter)
    (let ((result (sync (choose (recv-evt ch)
                                (wrap (sleep-evt 10.0) (lambda (_) 'timeout))))))
      (assert (= result iter))))
  (display "choose-recv-beats-timer passed\n"))

(do ((iter 0 (+ iter 1)))
    ((= iter 100))
  (let ((cv (make-condition)))
    (signal! cv)
    (let ((result (sync (choose
                          (wrap (wait-evt cv) (lambda (_) 'cond))
                          (wrap (sleep-evt 10.0) (lambda (_) 'timer))))))
      (assert (eq? result 'cond)))))
(display "choose-condition-beats-timer passed\n")

(let ((ch (make-channel 1)))
  (do ((i 0 (+ i 1)))
      ((= i 100))
    (send ch i)
    (let ((result (sync (choose (wrap (sleep-evt 10.0) (lambda (_) 'timeout))
                                (recv-evt ch)))))
      (assert (= result i))))
  (display "timer-loses passed\n"))

(let ((channels (let loop ((i 0) (acc '()))
                  (if (= i 5)
                      (reverse acc)
                      (loop (+ i 1) (cons (make-channel 1) acc))))))
  (for-each (lambda (ch) (send ch 'ready)) channels)
  (let ((evts (map recv-evt channels)))
    (let ((result (sync (apply choose evts))))
      (assert (eq? result 'ready))
      (display "all-ready passed\n"))))

(display "all stress-choose tests passed\n")
