(import (rnrs) (cml) (cml channels) (prefix (async) tokio/))

(let ((result-ch (make-channel 20)))
  (do ((i 0 (+ i 1)))
      ((= i 20))
    (let ((idx i))
      (tokio/spawn (lambda () (send result-ch idx)))))
  (let loop ((count 0) (sum 0))
    (if (= count 20)
        (begin
          (assert (= count 20))
          (assert (= sum 190)))
        (loop (+ count 1) (+ sum (recv result-ch))))))
(display "spawn-many passed\n")

(let ((chs (let loop ((i 0) (acc '()))
             (if (= i 11)
                 (reverse acc)
                 (loop (+ i 1) (cons (make-channel 1) acc))))))
  (let ((input-ch (car chs))
        (output-ch (list-ref chs 10)))
    (do ((stage 0 (+ stage 1)))
        ((= stage 10))
      (let ((in-ch (list-ref chs stage))
            (out-ch (list-ref chs (+ stage 1))))
        (tokio/spawn
          (lambda ()
            (send out-ch (+ (recv in-ch) 1))))))
    (send input-ch 0)
    (let ((result (recv output-ch)))
      (assert (= result 10)))))
(display "pipeline passed\n")

(let ((mutex (make-channel 1))
      (done1 (make-channel 1))
      (done2 (make-channel 1)))
  (send mutex 0)
  (tokio/spawn
    (lambda ()
      (do ((i 0 (+ i 1)))
          ((= i 25))
        (let ((val (recv mutex)))
          (send mutex (+ val 1))))
      (send done1 'ok)))
  (tokio/spawn
    (lambda ()
      (do ((i 0 (+ i 1)))
          ((= i 25))
        (let ((val (recv mutex)))
          (send mutex (+ val 1))))
      (send done2 'ok)))
  (recv done1)
  (recv done2)
  (assert (= (recv mutex) 50)))
(display "mutex-fairness passed\n")

(display "all stress-tasks tests passed\n")
